---

dist: bionic

language: python
addons:
  apt:
    update: true
    sources:
      - bridge-utils
      - dnsmasq-base
      - ebtables
      - libvirt-bin
      - libvirt-dev
      - qemu-kvm
      - qemu-utils
      - ruby-dev
      - purge
      - python3-openssl
      - ca-certificates
      - curl
      - gcc
      - iproute2
      - sudo
      - libvirt0
python:
  - "3.8"
  - "pypy3"
env:
  global:
    - VAGRANT_VER: 2.2.14

install:
  - |
    wget https://releases.hashicorp.com/vagrant/$VAGRANT_VER/vagrant_"$VAGRANT_VER"_x86_64.deb
    sudo apt -y install ./vagrant_"$VAGRANT_VER"_x86_64.deb
    vagrant plugin install vagrant-libvirt
  - |
    pip install wheel
    pip install netaddr python-vagrant yamllint testinfra flake8
    pip install ansible ansible-lint
    pip install molecule molecule-vagrant python-vagrant
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

script: travis_wait 30 sudo molecule test --scenario-name kvm