---
namespace: "tcharl"
name: "ansible_virtualization"
version: "1.0.1"
description: "Ansible roles that sets up all the prerequisites to bootstrap VMs on linux"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-virtualization"
documentation: "https://github.com/OsgiliathEnterprise/ansible-virtualization/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible-virtualization"
issues: "https://github.com/OsgiliathEnterprise/ansible-virtualization/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "linux"
  - "qemu"
  - "kvm"
