---
# tasks file for ansible-virtualization
- name: ansible-virtualization | import lvm playbook
  import_role:
    name: mrlesmithjr.manage-lvm
  become: true
  when: standalone_role

- name: ansible-virtualization | import user playbook
  import_role:
    name: tcharl.ansible_users
  become: true
  when: standalone_role


- name: ansible-virtualization | permanently allow traffic forwarding on host nic
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes

- name: ansible-virtualizatio | permanently allow traffic forwarding on host nic
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
