---
# tasks file for ansible-virtualization
- name: ansible-virtualization | disable dnsmaq
  ansible.builtin.systemd:
    name: dnsmasq
    state: stopped
    enabled: no
  become: yes

- name: ansible-virtualization | dependences
  ansible.builtin.include_tasks: requirements.yml
  when:
   - standalone_role is defined
   - standalone_role
  tags:
    - standalone

- name: ansible-virtualization | permanently allow traffic forwarding on host nic
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes

- name: ansible-virtualizatio | permanently allow traffic forwarding on host nic
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
