---
# tasks file for ansible-virtualization

- name: ansible-virtualization | restart libvirtd service
  service:
    name: libvirtd
    state: restarted
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['distribution_major_version'] | int < 32
  # see https://bugzilla.redhat.com/show_bug.cgi?id=1697636